### ISSUE TITLE
Add show ticket option

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/Seat-Booking#20]
Ticket should be store and retrieve on the basis of employee code. :+1:

**Comment by nemnous** [comment]
Sir, I'm looking forward to take up this. It would be more useful if you're more specific.

**Comment by pawank0411** [comment]
Add a Structured firebase to it,
google-json file already present.
Use hasp maps and store the tickets (data) in firebase and retrieve it for later use (Show ticket option) . :+1:

**Comment by pawank0411** [comment]
Go through saveSeats class,
i have added some comments, for your better understanding.

**Comment by ajaypro** [comment]
Hi, is this issue in progress or can I work on it.

**Comment by pawank0411** [comment]
you can work.
go ahead. :+1:

**Comment by ajaypro** [comment]
I'll start to work on this

**Comment by pawank0411** [comment]
Okay.

**Comment by ajaypro** [comment]
Hey Pawan, when i tried to open the app it is asking for employee code

**Comment by pawank0411** [comment]
enter 0000

**Comment by pawank0411** [comment]
You can get all these in Mainactivity class
