### ISSUE TITLE
LoginRegistration doesn't compile

### ISSUE THREAD

**Issue by didaRatsimba** [Pawan0411/Seat-Booking#24]
I was unable to build the project because in com.university.soa.bus.LoginRegistration class, there is a line that initialize a class called : SaveData that doesn't exist ? May be a bad refactoring ?

**Comment by didaRatsimba** [comment]
To build the project, I commented the two lines : 
```
SaveData saveData = new SaveData(str_name, str_empcode);
ref.push().setValue(saveData);
```

**Comment by pawank0411** [comment]
There's no need of LoginRegistration class.
