### ISSUE TITLE
Toast Currently selected seats

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/Seat-Booking#7]
Previously Selected seats should not be saved in firebase.

**Comment by AbdulDroid** [comment]
Can you provide more details to this behaviour and how to reproduce or track the changes to know if the issue has been fixed @Pawan0411

**Comment by geekykant** [comment]
Your code could have been more readable if you added comments. Friendly opinion :)

**Comment by pawank0411** [comment]
For now just Toast the currently selected seats after clicking "SaveInfo" button.👍 :)
